#Synapse API for Nukkit: config
disable-rak: false
enable: true
autoCompress: true
# 与 Nukkit network.input-dispatcher.enabled 同时开启才接入统一输入队列。
main-thread-input: false

entries:
  - server-ip: 127.0.0.1
    server-port: 10305
    isMainServer: true
    password: must16keyslength
    description: Synapse Nukkit Server
    autoConnect: true
