package org.itxtech.synapseapi.multiprotocol.utils.block;

public interface BlockStateIntegerValues {
    int MAX_AGE = 15;
    int MAX_BITE_COUNTER = 6;
    int MAX_BLOCK_LIGHT_LEVEL = 15;
    int MAX_BOOKS_STORED = 63;
    int MAX_BRUSHED_PROGRESS = 3;
    int MAX_CANDLES = 3;
    int MAX_CLUSTER_COUNT = 3;
    int MAX_COMPOSTER_FILL_LEVEL = 8;
    int MAX_CORAL_DIRECTION = 3;
    int MAX_CORAL_FAN_DIRECTION = 1;
    int MAX_DEPRECATED = 3;
    int MAX_DIRECTION = 3;
    int MAX_FACING_DIRECTION = 5;
    int MAX_FILL_LEVEL = 6;
    int MAX_GROUND_SIGN_DIRECTION = 15;
    int MAX_GROWING_PLANT_AGE = 25;
    int MAX_GROWTH = 7;
    int MAX_HEIGHT = 7;
    int MAX_HONEY_LEVEL = 5;
    int MAX_HUGE_MUSHROOM_BITS = 15;
    int MAX_KELP_AGE = 25;
    int MAX_LIQUID_DEPTH = 15;
    int MAX_MOISTURIZED_AMOUNT = 7;
    int MAX_MULTI_FACE_DIRECTION_BITS = 63;
    int MAX_PROPAGULE_STAGE = 4;
    int MAX_RAIL_DIRECTION = 9;
    int MAX_REDSTONE_SIGNAL = 15;
    int MAX_REPEATER_DELAY = 3;
    int MAX_RESPAWN_ANCHOR_CHARGE = 4;
    int MAX_ROTATION = 3;
    int MAX_SCULK_SENSOR_PHASE = 2;
    int MAX_STABILITY = 7;
    int MAX_TRIAL_SPAWNER_STATE = 5;
    int MAX_TWISTING_VINES_AGE = 25;
    int MAX_VINE_DIRECTION_BITS = 15;
    int MAX_WEEPING_VINES_AGE = 25;
    int MAX_WEIRDO_DIRECTION = 3;

    int CHORUS_FLOWER_MAX_AGE = 5;
    int COCOA_MAX_AGE = 2;
    int FROSTED_ICE_MAX_AGE = 3;
    int NETHER_WART_MAX_AGE = 3;

    int CHALKBOARD_MAX_DIRECTION = 15;

    int ACTIVATOR_RAIL_MAX_RAIL_DIRECTION = 5;
    int DETECTOR_RAIL_MAX_RAIL_DIRECTION = 5;
    int GOLDEN_RAIL_MAX_RAIL_DIRECTION = 5;
}
